### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Green-Sky** [Green-Sky/anno16_docs#5]
Currently there is no license. Since there is no code in this repo, i would choose some CC license.
Sugestions:
- CC-BY (by = attribution)
- CC-BY-SA (sa = share alike)
- CC-*-NC (nc = non commercial)

@siredmar @LsHallo

**Comment by LsHallo** [comment]
I would suggest CC BY-NC-SA 4.0.
So it can be used and expanded after we might abandon it.
NC part not necessary since I can't imagine some company using this repo for any sort of commercial purpose.

**Comment by Green-Sky** [comment]
> I would suggest CC BY-NC-SA 4.0.

I tend to that one too.

> NC part not necessary since I can't imagine some company using this repo for any sort of commercial purpose.

lol yea.

**Comment by Green-Sky** [comment]
I just realized @siredmar reacted with a :+1: ... Lesson learned: emoji reactions don't trigger notifications!
I will now add the CC BY-NC-SA 4.0
